### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by zener05** [Machy8/webloader#13]
Hi Machy8 👋

We would like to upgrade our app to PHP8 but there are some deprecated messages because of this package.

Could you add support for PHP8, please?

**Comment by Machy8** [comment]
I will look into it.

**Comment by Machy8** [comment]
@zener05 Could you please let me know if changes in this pull requests (branch) works in your project? Thanks https://github.com/Machy8/webloader/pull/14

**Comment by zener05** [comment]
It seems to be working well 👍 Thank you!

**Comment by Machy8** [comment]
@zener05 I have released a new version https://packagist.org/packages/machy8/webloader#v2.0.0. So check it out. Please let me know if you encounter any other issues.

**Comment by zener05** [comment]
We haven't upgraded to PHP8 yet so I can't give you proper feedback. But as I wrote it seemed to be working well during my tests.

I would let you know if there were any problems in future. Thank you :-)
