### ISSUE TITLE
The $this->template->setParameters(...); method is not available in Nette 3.1.

### ISSUE THREAD

**Issue by buffus** [Machy8/webloader#15]
The  `$this->template->setParameters(...); ` method is not available in Nette 3.1.
https://forum.nette.org/cs/33188-pojdme-otestovat-nette-application-3-1#p210845

How to set template parameters in Nette 3.1? Can I request a repair part of README.md below.? 
https://github.com/Machy8/webloader#quick-start-for-nette-framework

I don't know how to do it. Thanks.

**Comment by Machy8** [comment]
@buffus I am sorry for the late answer

Please, try the code below. It should set the one parameter you need. The setParameters sets multiple parameters according to given array. The code below sets parameter individually. 

You can read more here => https://doc.nette.org/cs/3.1/presenters#toc-promenne-v-sablone.

Let me know if it helps.

```PHP
$this->template->webloaderFilesCollectionRender = $this->webLoader->getFilesCollectionRender();
```

**Comment by buffus** [comment]
Yes it works well. Thank you.
