### ISSUE TITLE
Remove type attributes

### ISSUE THREAD

**Issue by buffus** [Machy8/webloader#16]
Hi Machy8,

I think that `type="text/css"` and `type="text/javascript"` attributes are unnecessary for HTML5.

- https://html.spec.whatwg.org/multipage/semantics.html#processing-the-type-attribute
- https://html.spec.whatwg.org/multipage/scripting.html#the-script-element

If `<script type="text/javascript">` is used in the code the [validator.w3.org](https://validator.w3.org/) reports
_Warning: The type attribute is unnecessary for JavaScript resources._

The following outputs from Machy8/webloader would be sufficient:

- `<link rel="stylesheet" href="my-bundle.css?v=...">`
- `<script src="my-bundle.js?v=..."></script>`

Could you add support for HTML5 (remove type attributes), please?

**Comment by Machy8** [comment]
@buffus Thanks for report. I will look into it.

**Comment by Machy8** [comment]
@buffus I am sorry for the delay. I have been working on the https://stylify.dev/ project a lot recently. 
Anyway the patch version has been released https://github.com/Machy8/webloader/releases/tag/v2.0.1.

Thanks again for the issue!, and Happy Holidays :).
